### ISSUE TITLE
USAGE

### ISSUE THREAD

**Issue by eh891l3b** [tecan/QFax#1]
How do i use this to send a fax?

**Comment by netpipe** [comment]
well, its not really ready yet(backend works but frontend needs to be connected to backend). what ide like to do is freelance the rest of it but i have too many ongoing projects for my assisted living income and the no money i've ever made online. use an online service like www.faxzero.com to send free faxes online. (also android has an app like this i think) there are hamradio apps too that can fax.

**Comment by netpipe** [comment]
its based on something that worked previously and the qt app can send all the commandline args so technically it is working but needs the GUI portion finished.

**Comment by ghost** [comment]
Ok. so what command line args would I run?

**Comment by netpipe** [comment]
https://github.com/netpipe/QFax/blob/master/linmodem/README here is the original application it has a CLI to play with and can be used like regular console app. there is a GTK frontend for it aswell but this repo is the QT version.

**Comment by netpipe** [comment]
http://efax-gtk.sourceforge.net/
http://www.enst.fr/~bellard/linmodem.html
